
services:
  db:
    image: mysql:8.0.44
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dogs
      MYSQL_DATABASE: cwa_db
    user: 1000:1000
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
  frontend:
    image: node:20-alpine
    container_name: nextjs-dev
    working_dir: /app
    user: 1000:1000
    shm_size: 1g
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./web:/app
    environment:
      - NODE_ENV=development

  backend:
    image: python:3.12
    user: 1000:1000
    working_dir: /app
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./backend:/app
      - ./mysql/migrations:/app/mysql/migrations:ro
    command: /bin/bash -c "python -m venv venv && source venv/bin/activate && pip install -r requirements.txt && gunicorn -b 0.0.0.0:8000 main:app"
    depends_on: [db]
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8000 
      # ===== EMAIL CONFIG =====
      - CONTACT_TO_EMAIL=##YOUR_CONTACT_EMAIL_HERE##
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=##YOUR_CONTACT_EMAIL_HERE##
      - SMTP_PASS=##GOOGLE_APP_PASSWORD##
      - FROM_EMAIL=##YOUR_CONTACT_EMAIL_HERE##

  nginx:
    image: nginx:alpine
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  data:
